-- =============================================================
-- v67_payment_methods_free_icon.sql
-- AttenDo LMS — Remove the CHECK constraint on payment_methods.icon
-- so teachers can supply a custom emoji (e.g., '💰', '🏦', '⚡')
-- instead of being limited to the 7 preset lucide icon names.
--
-- Migration is idempotent.
-- =============================================================

-- 1. Drop the icon CHECK constraint (the name was auto-generated by
--    Postgres when v66 created the column; the constraint name might
--    be either 'payment_methods_icon_check' or 'payment_methods_icon'
--    depending on the PG version. Try both.
ALTER TABLE public.payment_methods
  DROP CONSTRAINT IF EXISTS payment_methods_icon_check;

ALTER TABLE public.payment_methods
  DROP CONSTRAINT IF EXISTS payment_methods_icon;

-- (No new constraint added. Column stays TEXT — accepts any short
--  string: a lucide preset name OR an emoji OR a custom short label.)
